### ISSUE TITLE
Your object output, could you update it to include the last logon date

### ISSUE THREAD

**Issue by BlackV** [Foyerr/Audit-UserShare#1]
as per your example    

Audit-UserShare -folderSize -searchDir \\server\users -daysSinceLogin 30
        SamAccountName Enabled No Account Lastlogon
        -------------- ------- ---------- ----------
        TestUser1         True      False       2021/03/23
        TestUser2         True      False       2020/12/01
        TestUser3        False      False       2021/04/20
        TestUser4        False      False       2017/11/19
        TestUser5         True      False       2022/01/01
        TestUser6         True      False       2019/07/13
        TestUser7         True      False       2016/18/16
        LargeUserFolder    N/A       True       2021/03/11
        TestUser9         True      False       2015/03/06

an additional column including the date of that days since logon value

**Comment by Foyerr** [comment]
Yeah, shouldn't be a problem!
I'll push up the change

**Comment by Foyerr** [comment]
Commited change
